require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/gradclasses', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Gradclass. As you add validations to Gradclass, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Gradclass.create! valid_attributes
      get gradclasses_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      gradclass = Gradclass.create! valid_attributes
      get gradclass_url(gradclass)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_gradclass_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      gradclass = Gradclass.create! valid_attributes
      get edit_gradclass_url(gradclass)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Gradclass' do
        expect do
          post gradclasses_url, params: { gradclass: valid_attributes }
        end.to change(Gradclass, :count).by(1)
      end

      it 'redirects to the created gradclass' do
        post gradclasses_url, params: { gradclass: valid_attributes }
        expect(response).to redirect_to(gradclass_url(Gradclass.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Gradclass' do
        expect do
          post gradclasses_url, params: { gradclass: invalid_attributes }
        end.to change(Gradclass, :count).by(0)
      end


      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post gradclasses_url, params: { gradclass: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested gradclass' do
        gradclass = Gradclass.create! valid_attributes
        patch gradclass_url(gradclass), params: { gradclass: new_attributes }
        gradclass.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the gradclass' do
        gradclass = Gradclass.create! valid_attributes
        patch gradclass_url(gradclass), params: { gradclass: new_attributes }
        gradclass.reload
        expect(response).to redirect_to(gradclass_url(gradclass))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        gradclass = Gradclass.create! valid_attributes
        patch gradclass_url(gradclass), params: { gradclass: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested gradclass' do
      gradclass = Gradclass.create! valid_attributes
      expect do
        delete gradclass_url(gradclass)
      end.to change(Gradclass, :count).by(-1)
    end

    it 'redirects to the gradclasses list' do
      gradclass = Gradclass.create! valid_attributes
      delete gradclass_url(gradclass)
      expect(response).to redirect_to(gradclasses_url)
    end
  end
end
